language: java
jdk: openjdk8
sudo: false

services:
  - docker

env:
  global:
  - secure: "Av0mTC2Z7p1aq3gPryhq40tZOryuceSR+FzYb+QSwEW7i26kdMwfJLgi1d/eqp7OkY8yyk5h+F6cyxKxQYhEHb1neVSrirYh8U+YJPkJ+sDT8rZmFkKeh6ky/bMf7zyl57FyobimCXVgBME4s0jIrPbuPxiWgXtKXKlIKzrRIz9tQ1rRplRE+bKeO2CzONQn1qKE67+AauA0KvsHMm2hdNpWKWU0J2YQXOBRQ6eeEhY6ZFLL8v7ow9YSWtJ6iTADU8NCE4MwTnG13FHztaC1pX5QPeWDQ+rI66e7RHMl51S+t7uYDPnkY/mkWw4Mb5+Oxn+IJPBBWQFmgi4KFQ3C8/JD52zYdlLgbvHz7IIFHcUV/aNbVVpdeY/mEKaPBKc2HgpjFDNLGQIQeVUC1mgltRUBnRMAkYeviqfkB5t+MxIGKcBem6pwmymDQ03dnCGfmRCHREJDTSAICpBOtcstr1SrMg9IYRT+rjBc25hCBAnK8yptrcazfdidkkw1icktv+5boyv8YUChqGxkIO/P2LUQpNvQEsoL53qhyoTi3dhLVCxyUCr9ENd1+DLtUBPDRsDpUpJ3urNXgRmW132PJO0Bs/7orfFMnZMlllpgo/2IEGdjaRRHiJT8YezVTaZk5dc2+klAV0J4Yc3X0lfpI5c7d7oyPXHac0onrZvk1mA="
  - secure: "VhJlfWkNv2lOaWFDJ23S11G3H58+9vRtcZZcBFr1APhg7TeS3U7+1LhNGGyzuYENH2RM7cj+08Km2o+3HfDIPpyTXRBX+iAp1GVhhVGhvuYjTbJk/Tc7R7f2a6MFK3TUmBwcyXbv5xHqsI7YxjvTMHk/2v0Ozj0qkmQcXSiGos/X7TtiVZCHFhKn6D9SCjNlrXjiwu5qlwOkGZVW28lL9CdKW3ATz2qsKuaTyJcfwHilYFGQqAq9dgg9bhj4jZa7oWJsw+j7HaJXxZmgaMroa0rx8Fe4PtwCSU8troHX6Q0comYPHBMzp/n1I92MH7FcireEI2AHDuMzcYvugcXnzunM3UKKkA8z5XSxrmqoKdYF6SNkHY/mvsolGx7xU4KrtWXBnoMTxljK2j8gz4h7SImEnIjl2q88jMmR+yYFbYuRDIc7oRPajO7Ap6TnR7vuT4EaPbIfKmuGu+yz/AmLyi612oDcY79VL2yosplVqpKzClByoP8+A2iqqxX+1KlRDlnANlLrhOdQvbENR52RwJ64Y7EJDnDbW1zcxpiH8j4+gn/FkEGxHY64KgwonsQXCuOREbsHR1NSH9mGEwgX6qaOi5MyM8DPYpVBHLZ20xXyIAAd+v4NT8myeqesNuD0VQiOGZVcNR5qYufoOqyh/8Qv9Pn6znHUdtBkj8E44Jg="
  - secure: "GSMC6dbb8pt4vnFpybhyJZ0CiyyeJ7Wbf5XeRoTS25OpgyDtbyE3l2ZWpMVAfx0JJ9LEYaVmjjr0GgRt3x7jnoG8FQcF6bP5hcbhYNQ82qZM9SuwQ5A8mTRPsJp7WLQvWmr6x3QtUV42aVrHIIm6hxQU8vm8n94ly/8cM+TL1EMayyGnTO41+C5Gs/+7KHjFzs2zSkgoMvWWI43rqrxhEBwCLOZC7jCDhXMkaRFZ+YGl7lw1Zt9Yl9ZC6/7n1BxgqOw4DAKMjEjxjBch4UQ6D3lZhmi8AXVJgI/T+oCJ5PaN38q0ZVwnfljsVqnNx/MVW9zd7CrXcTYhMlSVTyAEPzuZz/PlxVpxpCYBiiFPY67oq0hAFrHP9DKC72IKQxoU+aV/Ny17e2/OyXFx8gg4uG7gtAShm94TyFdiBK4aTDiau2czxr5LzyGvhunjzmafhinjYOrNzleikzJTuMry584yQjV0YwzeJID/9bffly1fE7+slRKFnuYXQNsG4NAJMfw0UIDvi8fiJy6gXV9Zh50MqMPY6CEiQqd+FI83BzfwAaO+mL7kw0KNrgBagPK0EEKsmFQMDjJpuwg1F/4AvbrpEKpjVzGCPWTxi83YN9KIovutbR82rUZ3C9K1xiGIcDn0TNEAnfi04bfno5LiBG0tPYq3YP493V7CiZi1Tv8="
  - COMMIT=${TRAVIS_COMMIT::7}
  - IMAGE_NAME=todo-api-spring-boot-newman


addons:
  sonarcloud:
    organization: "sam-kaz-github"
    token:
      secure: $SONAR_TOKEN

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - ./mvnw sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export DOCKER_IMAGE=$DOCKER_USER/$IMAGE_NAME
  - docker build -t $DOCKER_IMAGE:$COMMIT .
  - docker tag $DOCKER_IMAGE:$COMMIT $DOCKER_IMAGE:$TAG
  - docker push $DOCKER_IMAGE

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: todo-api-spring-boot-new
  on:
    branch: master
